# 데이터 테스트를 위한 H2 db 연결
spring:
  profiles:
    default: local
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  output:
    ansi:
      enabled: always
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.type: trace

jwt:
  secret-key: ${jwt.secret-key}
  access-token-expired-time: ${jwt.access-token-expired-time}
  refresh-token-expired-time: ${jwt.refresh-token-expired-time}
