# 데이터 테스트를 위한 H2 db 연결

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:h2:tcp://localhost/~/toy
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.type: trace
